# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """─── 4 типа gRPC-вызовов ───────────────────────────────────────────────────

    1. Unary:             клиент → 1 запрос, сервер → 1 ответ
    2. Server streaming:  клиент → 1 запрос, сервер → N ответов (stream)
    3. Client streaming:  клиент → N запросов (stream), сервер → 1 ответ
    4. Bidirectional:     клиент → N запросов, сервер → N ответов (stream)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItem = channel.unary_unary(
                '/streaming.DataService/GetItem',
                request_serializer=streaming__pb2.ItemRequest.SerializeToString,
                response_deserializer=streaming__pb2.Item.FromString,
                _registered_method=True)
        self.ListItems = channel.unary_stream(
                '/streaming.DataService/ListItems',
                request_serializer=streaming__pb2.ListRequest.SerializeToString,
                response_deserializer=streaming__pb2.Item.FromString,
                _registered_method=True)
        self.AddItems = channel.stream_unary(
                '/streaming.DataService/AddItems',
                request_serializer=streaming__pb2.Item.SerializeToString,
                response_deserializer=streaming__pb2.Summary.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/streaming.DataService/Chat',
                request_serializer=streaming__pb2.ChatMessage.SerializeToString,
                response_deserializer=streaming__pb2.ChatMessage.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """─── 4 типа gRPC-вызовов ───────────────────────────────────────────────────

    1. Unary:             клиент → 1 запрос, сервер → 1 ответ
    2. Server streaming:  клиент → 1 запрос, сервер → N ответов (stream)
    3. Client streaming:  клиент → N запросов (stream), сервер → 1 ответ
    4. Bidirectional:     клиент → N запросов, сервер → N ответов (stream)

    """

    def GetItem(self, request, context):
        """1. Unary — обычный запрос-ответ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """2. Server streaming — сервер шлёт пачку данных
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItems(self, request_iterator, context):
        """3. Client streaming — клиент шлёт пачку, сервер подводит итог
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """4. Bidirectional streaming — чат
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=streaming__pb2.ItemRequest.FromString,
                    response_serializer=streaming__pb2.Item.SerializeToString,
            ),
            'ListItems': grpc.unary_stream_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=streaming__pb2.ListRequest.FromString,
                    response_serializer=streaming__pb2.Item.SerializeToString,
            ),
            'AddItems': grpc.stream_unary_rpc_method_handler(
                    servicer.AddItems,
                    request_deserializer=streaming__pb2.Item.FromString,
                    response_serializer=streaming__pb2.Summary.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=streaming__pb2.ChatMessage.FromString,
                    response_serializer=streaming__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """─── 4 типа gRPC-вызовов ───────────────────────────────────────────────────

    1. Unary:             клиент → 1 запрос, сервер → 1 ответ
    2. Server streaming:  клиент → 1 запрос, сервер → N ответов (stream)
    3. Client streaming:  клиент → N запросов (stream), сервер → 1 ответ
    4. Bidirectional:     клиент → N запросов, сервер → N ответов (stream)

    """

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.DataService/GetItem',
            streaming__pb2.ItemRequest.SerializeToString,
            streaming__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streaming.DataService/ListItems',
            streaming__pb2.ListRequest.SerializeToString,
            streaming__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItems(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/streaming.DataService/AddItems',
            streaming__pb2.Item.SerializeToString,
            streaming__pb2.Summary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/streaming.DataService/Chat',
            streaming__pb2.ChatMessage.SerializeToString,
            streaming__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
