# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\x19\n\x0bItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x0bListRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ilter\x18\x02 \x01(\t\"/\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"-\n\x07Summary\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x13\n\x0btotal_price\x18\x02 \x01(\x02\"6\n\x0b\x43hatMessage\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0b\n\x03seq\x18\x03 \x01(\x05\x32\xe8\x01\n\x0b\x44\x61taService\x12\x32\n\x07GetItem\x12\x16.streaming.ItemRequest\x1a\x0f.streaming.Item\x12\x36\n\tListItems\x12\x16.streaming.ListRequest\x1a\x0f.streaming.Item0\x01\x12\x31\n\x08\x41\x64\x64Items\x12\x0f.streaming.Item\x1a\x12.streaming.Summary(\x01\x12:\n\x04\x43hat\x12\x16.streaming.ChatMessage\x1a\x16.streaming.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=30
  _globals['_ITEMREQUEST']._serialized_end=55
  _globals['_LISTREQUEST']._serialized_start=57
  _globals['_LISTREQUEST']._serialized_end=105
  _globals['_ITEM']._serialized_start=107
  _globals['_ITEM']._serialized_end=154
  _globals['_SUMMARY']._serialized_start=156
  _globals['_SUMMARY']._serialized_end=201
  _globals['_CHATMESSAGE']._serialized_start=203
  _globals['_CHATMESSAGE']._serialized_end=257
  _globals['_DATASERVICE']._serialized_start=260
  _globals['_DATASERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
