# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import errors_pb2 as errors__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in errors_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculatorStub(object):
    """─── Обработка ошибок в gRPC ───────────────────────────────────────────────
    В REST ошибки передаются через HTTP-статус + JSON-тело.
    В gRPC — через grpc.StatusCode + детальное сообщение.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Divide = channel.unary_unary(
                '/errors.Calculator/Divide',
                request_serializer=errors__pb2.DivideRequest.SerializeToString,
                response_deserializer=errors__pb2.DivideResponse.FromString,
                _registered_method=True)
        self.Sqrt = channel.unary_unary(
                '/errors.Calculator/Sqrt',
                request_serializer=errors__pb2.SqrtRequest.SerializeToString,
                response_deserializer=errors__pb2.SqrtResponse.FromString,
                _registered_method=True)


class CalculatorServicer(object):
    """─── Обработка ошибок в gRPC ───────────────────────────────────────────────
    В REST ошибки передаются через HTTP-статус + JSON-тело.
    В gRPC — через grpc.StatusCode + детальное сообщение.

    """

    def Divide(self, request, context):
        """Divide — деление с защитой от zero division
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sqrt(self, request, context):
        """Sqrt — квадратный корень (отрицательное число → ошибка)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=errors__pb2.DivideRequest.FromString,
                    response_serializer=errors__pb2.DivideResponse.SerializeToString,
            ),
            'Sqrt': grpc.unary_unary_rpc_method_handler(
                    servicer.Sqrt,
                    request_deserializer=errors__pb2.SqrtRequest.FromString,
                    response_serializer=errors__pb2.SqrtResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'errors.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('errors.Calculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """─── Обработка ошибок в gRPC ───────────────────────────────────────────────
    В REST ошибки передаются через HTTP-статус + JSON-тело.
    В gRPC — через grpc.StatusCode + детальное сообщение.

    """

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/errors.Calculator/Divide',
            errors__pb2.DivideRequest.SerializeToString,
            errors__pb2.DivideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sqrt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/errors.Calculator/Sqrt',
            errors__pb2.SqrtRequest.SerializeToString,
            errors__pb2.SqrtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
