# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: errors.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'errors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65rrors.proto\x12\x06\x65rrors\"%\n\rDivideRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\" \n\x0e\x44ivideResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\"\x1d\n\x0bSqrtRequest\x12\x0e\n\x06number\x18\x01 \x01(\x01\"\x1e\n\x0cSqrtResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32x\n\nCalculator\x12\x37\n\x06\x44ivide\x12\x15.errors.DivideRequest\x1a\x16.errors.DivideResponse\x12\x31\n\x04Sqrt\x12\x13.errors.SqrtRequest\x1a\x14.errors.SqrtResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'errors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIVIDEREQUEST']._serialized_start=24
  _globals['_DIVIDEREQUEST']._serialized_end=61
  _globals['_DIVIDERESPONSE']._serialized_start=63
  _globals['_DIVIDERESPONSE']._serialized_end=95
  _globals['_SQRTREQUEST']._serialized_start=97
  _globals['_SQRTREQUEST']._serialized_end=126
  _globals['_SQRTRESPONSE']._serialized_start=128
  _globals['_SQRTRESPONSE']._serialized_end=158
  _globals['_CALCULATOR']._serialized_start=160
  _globals['_CALCULATOR']._serialized_end=280
# @@protoc_insertion_point(module_scope)
