# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bookstore_pb2 as bookstore__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bookstore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookstoreStub(object):
    """─── gRPC-спецификация сервиса книжного магазина ───────────────────────────
    Те же CRUD-операции, что в REST-версии из лекции 2,
    но через protobuf — строгая типизация, компактный бинарный формат.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBooks = channel.unary_unary(
                '/bookstore.Bookstore/ListBooks',
                request_serializer=bookstore__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=bookstore__pb2.ListBooksResponse.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/bookstore.Bookstore/GetBook',
                request_serializer=bookstore__pb2.GetBookRequest.SerializeToString,
                response_deserializer=bookstore__pb2.Book.FromString,
                _registered_method=True)
        self.CreateBook = channel.unary_unary(
                '/bookstore.Bookstore/CreateBook',
                request_serializer=bookstore__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=bookstore__pb2.Book.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/bookstore.Bookstore/UpdateBook',
                request_serializer=bookstore__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=bookstore__pb2.Book.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/bookstore.Bookstore/DeleteBook',
                request_serializer=bookstore__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=bookstore__pb2.DeleteBookResponse.FromString,
                _registered_method=True)


class BookstoreServicer(object):
    """─── gRPC-спецификация сервиса книжного магазина ───────────────────────────
    Те же CRUD-операции, что в REST-версии из лекции 2,
    но через protobuf — строгая типизация, компактный бинарный формат.

    """

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookstoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=bookstore__pb2.ListBooksRequest.FromString,
                    response_serializer=bookstore__pb2.ListBooksResponse.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=bookstore__pb2.GetBookRequest.FromString,
                    response_serializer=bookstore__pb2.Book.SerializeToString,
            ),
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=bookstore__pb2.CreateBookRequest.FromString,
                    response_serializer=bookstore__pb2.Book.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=bookstore__pb2.UpdateBookRequest.FromString,
                    response_serializer=bookstore__pb2.Book.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=bookstore__pb2.DeleteBookRequest.FromString,
                    response_serializer=bookstore__pb2.DeleteBookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.Bookstore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bookstore.Bookstore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bookstore(object):
    """─── gRPC-спецификация сервиса книжного магазина ───────────────────────────
    Те же CRUD-операции, что в REST-версии из лекции 2,
    но через protobuf — строгая типизация, компактный бинарный формат.

    """

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.Bookstore/ListBooks',
            bookstore__pb2.ListBooksRequest.SerializeToString,
            bookstore__pb2.ListBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.Bookstore/GetBook',
            bookstore__pb2.GetBookRequest.SerializeToString,
            bookstore__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.Bookstore/CreateBook',
            bookstore__pb2.CreateBookRequest.SerializeToString,
            bookstore__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.Bookstore/UpdateBook',
            bookstore__pb2.UpdateBookRequest.SerializeToString,
            bookstore__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.Bookstore/DeleteBook',
            bookstore__pb2.DeleteBookRequest.SerializeToString,
            bookstore__pb2.DeleteBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
