# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookstore.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bookstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62ookstore.proto\x12\tbookstore\"\\\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\x0c\n\x04isbn\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x01\"<\n\x10ListBooksRequest\x12\x18\n\x0byear_filter\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x0e\n\x0c_year_filter\"3\n\x11ListBooksResponse\x12\x1e\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0f.bookstore.Book\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"]\n\x11\x43reateBookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\x0c\n\x04isbn\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\"i\n\x11UpdateBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\x0c\n\x04isbn\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x01\"\x1f\n\x11\x44\x65leteBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteBookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xcf\x02\n\tBookstore\x12\x46\n\tListBooks\x12\x1b.bookstore.ListBooksRequest\x1a\x1c.bookstore.ListBooksResponse\x12\x35\n\x07GetBook\x12\x19.bookstore.GetBookRequest\x1a\x0f.bookstore.Book\x12;\n\nCreateBook\x12\x1c.bookstore.CreateBookRequest\x1a\x0f.bookstore.Book\x12;\n\nUpdateBook\x12\x1c.bookstore.UpdateBookRequest\x1a\x0f.bookstore.Book\x12I\n\nDeleteBook\x12\x1c.bookstore.DeleteBookRequest\x1a\x1d.bookstore.DeleteBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=30
  _globals['_BOOK']._serialized_end=122
  _globals['_LISTBOOKSREQUEST']._serialized_start=124
  _globals['_LISTBOOKSREQUEST']._serialized_end=184
  _globals['_LISTBOOKSRESPONSE']._serialized_start=186
  _globals['_LISTBOOKSRESPONSE']._serialized_end=237
  _globals['_GETBOOKREQUEST']._serialized_start=239
  _globals['_GETBOOKREQUEST']._serialized_end=267
  _globals['_CREATEBOOKREQUEST']._serialized_start=269
  _globals['_CREATEBOOKREQUEST']._serialized_end=362
  _globals['_UPDATEBOOKREQUEST']._serialized_start=364
  _globals['_UPDATEBOOKREQUEST']._serialized_end=469
  _globals['_DELETEBOOKREQUEST']._serialized_start=471
  _globals['_DELETEBOOKREQUEST']._serialized_end=502
  _globals['_DELETEBOOKRESPONSE']._serialized_start=504
  _globals['_DELETEBOOKRESPONSE']._serialized_end=541
  _globals['_BOOKSTORE']._serialized_start=544
  _globals['_BOOKSTORE']._serialized_end=879
# @@protoc_insertion_point(module_scope)
